function difference = autogen_difference(boardMass,boardTheta,boardHeight,boardLength,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,bottomMotorTorque,g,topLinkRCoM,topLinkMass,topLinkTheta,topMotorTorque)
%AUTOGEN_DIFFERENCE
%    DIFFERENCE = AUTOGEN_DIFFERENCE(BOARDMASS,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,BOTTOMMOTORTORQUE,G,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPMOTORTORQUE)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jun-2020 17:18:26

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = boardTheta+bottomLinkTheta;
t5 = boardHeight.*t3;
t6 = sin(t4);
t7 = t4+topLinkTheta;
t10 = (boardLength.*t2)./2.0;
t8 = sin(t7);
t9 = bottomLinkHeight.*t6;
t12 = -t10;
t11 = t8.*topLinkRCoM;
difference = [g.*(topLinkMass.*(t5+t9+t11+t12)+bottomLinkMass.*(t5+t12+bottomLinkRCoM.*t6)+boardMass.*(t5./2.0+t12));bottomMotorTorque+g.*(topLinkMass.*(t9+t11)+bottomLinkRCoM.*bottomLinkMass.*t6);topMotorTorque+g.*t11.*topLinkMass];
