function x_wheel_left_rel = autogen_wheel_position_3DOF(boardMass,boardTheta,boardHeight,boardLength,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_WHEEL_POSITION
%    X_WHEEL_LEFT_REL = AUTOGEN_WHEEL_POSITION(BOARDMASS,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jun-2020 17:46:44

t2 = sin(boardTheta);
t3 = boardTheta+bottomLinkTheta;
t4 = sin(t3);
x_wheel_left_rel = (boardHeight.*t2)./2.0+(topLinkRCoM.*topLinkMass.*sin(t3+topLinkTheta).*2.0+boardHeight.*bottomLinkMass.*t2+bottomLinkRCoM.*bottomLinkMass.*t4.*2.0+boardHeight.*t2.*topLinkMass+bottomLinkHeight.*t4.*topLinkMass.*2.0)./(boardMass.*2.0+bottomLinkMass.*2.0+topLinkMass.*2.0)-(boardLength.*cos(boardTheta))./2.0;
