function G_jac = autogen_derivative_conservative_forces_3DOF(boardMass,boardTheta,boardHeight,boardLength,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,g,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_DERIVATIVE_CONSERVATIVE_FORCES
%    G_JAC = AUTOGEN_DERIVATIVE_CONSERVATIVE_FORCES(BOARDMASS,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,G,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jun-2020 17:48:42

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = boardTheta+bottomLinkTheta;
t5 = boardHeight.*t2;
t6 = cos(t4);
t7 = t4+topLinkTheta;
t10 = (boardLength.*t3)./2.0;
t8 = cos(t7);
t9 = bottomLinkHeight.*t6;
t11 = bottomLinkRCoM.*bottomLinkMass.*t6;
t12 = t8.*topLinkRCoM;
t13 = g.*t12.*topLinkMass;
t15 = t9+t12;
t14 = -t13;
t16 = t15.*topLinkMass;
t17 = t11+t16;
t18 = g.*t17;
t19 = -t18;
G_jac = reshape([-g.*(bottomLinkMass.*(t5+t10+bottomLinkRCoM.*t6)+boardMass.*(t5./2.0+t10)+topLinkMass.*(t5+t10+t15)),t19,t14,t19,t19,t14,t14,t14,t14],[3,3]);
