function x_wheel = autogen_wheel_position(boardX,boardTheta,boardHeight,boardLength)
%AUTOGEN_WHEEL_POSITION
%    X_WHEEL = AUTOGEN_WHEEL_POSITION(BOARDX,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Jan-2021 17:40:02

x_wheel = boardX-(boardLength.*cos(boardTheta))./2.0+(boardHeight.*sin(boardTheta))./2.0;
